name: 'fitbod'
version: '1.0.0'

profile: 'fitbod'

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
    - "target"
    - "logs"
    - "dbt_packages"

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
config-version: 2
models:
  materialized: table

seeds:
  fitbod:
    quote_columns: false
    latest_users:
      +column_types:
        user_id: varchar
        email: varchar
    latest_aliases:
      +column_types:
        timestamp: double precision
        user_id: varchar
        alias_user_id: varchar
    latest_events:
      +column_types:
        timestamp: double precision
        user_id: varchar
        feature_key: varchar
        feature_value: varchar
