version: '3.8'

services:
    postgres:
        image: postgres:15
        container_name: postgres
        restart: always
        environment:
          POSTGRES_USER: dbt
          POSTGRES_PASSWORD: password1
          POSTGRES_DB: fitbod
          POSTGRES_INITDB_ARGS: "--auth-local=md5"
          POSTGRES_AUTOCOMMIT: OFF
        ports:
          - 5432:5432
        networks:
          - backend
        logging:
          driver: none 

    dbt:
        build:
          context: ./dbt
          dockerfile: Dockerfile
        container_name: dbt
        volumes:
          - ./data:/data
          - ./dbt:/dbt
        command: /bin/bash -c "chmod +x /dbt/dbt_entrypoint.sh && /dbt/dbt_entrypoint.sh"
        ports: 
          - 8080:8080
        networks:
          - backend
        links:
          - postgres
        depends_on:
          - postgres

networks:
  backend:
    driver: "bridge"
